apiVersion: apps/v1
kind: Deployment
metadata:
  name: team2-mlops
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team2
  template:
    metadata:
      labels:
        app: team2
    spec:
      containers:
      - name: team2-mlops
        image: yannchoho/team2:master
        ports:
        - containerPort: 5000
